version: '3'
 
services:
  mysql:
    image: tugrove/demosite04_mysql8.0.23:1.0
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    container_name: demosite04_mysql

  php_apache:
    depends_on:
      - mysql
    image: tugrove/demosite04_php8.0.3-apache:1.0
    volumes:
      - ./html:/var/www/html
    ports:
      - 50080:80
    environment:
      PHP_DB_HOST: demosite04_mysql
      PHP_DB_NAME: shop
      PHP_DB_USER: php
      PHP_DB_PASSWORD: php
    container_name: demosite04_php
